version: "3.8"

services:
  frontend-service:
    image: frontend-2.10
    container_name: frontend-container

    environment:
      - REACT_APP_BACKEND_URL=http://localhost/api

  backend-service:
    image: backend
    environment:
      - REDIS_HOST=redis-service
      - POSTGRES_HOST=postgres-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - REQUEST_ORIGIN=http://localhost
    container_name: backend-container
    depends_on:
      - postgres-service
      - redis-service

  redis-service:
    image: redis
    restart: unless-stopped
    container_name: redis-container

  postgres-service:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    container_name: postgres-container
    volumes:
      - ./db:/var/lib/postgresql/data

  reverse_proxy:
    image: nginx:1.19-alpine
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    environment:
      - NGINX_PORT=80

volumes:
    db:

