version: "3.8"

services:
  frontend-service:
    image: frontend
    ports:
      - 5000:5000
    container_name: frontend-container

  backend-service:
    image: backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis-service
      - POSTGRES_HOST=postgres-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    container_name: backend-container
    depends_on:
      - postgres-service
      - redis-service

  redis-service:
    image: redis
    restart: unless-stopped
    container_name: redis-container

  postgres-service:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    container_name: postgres-container

  reverse_proxy:
    image: nginx:1.19-alpine
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    environment:
      - NGINX_PORT=80
